kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name:  myapp-dc
spec:
  template: 
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: zhamdaoui/myapp-web-app:v2
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 3 
  strategy: 
    type: "Rolling"
  paused: false 
  revisionHistoryLimit: 2 