apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: asv
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: openshift/hello-openshift
    ports:
        - containerPort: 8080
          protocol: TCP